---

- name: Create Quipucords server home directory
  file:
    path: "{{server_install_dir}}"
    state: directory

- name: Create Quipucords server directory for logs
  file:
    path: "{{server_install_dir}}/log"
    state: directory

- name: Create Quipucords server directory for ssh keys
  file:
    path: "{{server_install_dir}}/sshkeys"
    state: directory

- name: Create Quipucords server directory for data
  file:
    path: "{{server_install_dir}}/data"
    state: directory

- name: Open Quipucords server port in firewall on host machine
  iptables:
    chain: INPUT
    destination_port: "{{ server_port }}"
    protocol: tcp
    jump: ACCEPT
  become: true
  ignore_errors: yes
  when:
    - open_port|bool

- name: Default SE Linux directory mounting to empty string
  set_fact:
    dir_mount_selinux: ""

- name: Set SE Linux mount directory to ":z" when SE Linux is enabled
  set_fact:
    dir_mount_selinux: ":z"
  when: selinux_on|bool

- name: Set the Quipucords server container image tag to user specified version
  set_fact:
    server_image_tag: "{{ server_version }}"
  when:
    - server_version is defined

- name: Set the Quipucords release server image file name
  set_fact:
    github_server_filename: "quipucords_server_image.tar.gz"

- name: Set the Quipucords release server image file name
  set_fact:
    release_cache_server_filename: "quipucords.{{ server_image_tag }}.tar.gz"

- name: Set Quipucords server container image name
  set_fact:
    server_image_name: "quipucords"

- name: Set Quipucords container image and tag
  set_fact:
    server_image_and_tag: "{{server_image_name}}:{{server_image_tag}}"
  when: server_image_and_tag is not defined

- name: Check for Quipucords server image presence
  shell: "podman images | grep {{ server_image_name }} | grep {{ server_image_tag }}"
  become: true
  register: quipucords_image_raw
  ignore_errors: yes

- name: Set Quipucords container image presence to false (default)
  set_fact:
    quipucords_image_present: false
  when:
    - quipucords_image_raw.rc != 0

- name: Set Quipucords container image presence to true if image present
  set_fact:
    quipucords_image_present: "{{ quipucords_image_raw['stdout_lines']|length > 0 }}"
  when:
    - quipucords_image_raw.rc == 0
    - "'stdout_lines' in quipucords_image_raw"

- name: Set path to Quipucords server container image file
  set_fact:
    qpc_server_version_filename: "{{ pkg_install_dir }}{{ release_cache_server_filename }}"
  when: qpc_server_version_filename is not defined

- name: Create local packages directory if it does not exist
  file:
    path: "{{ pkg_install_dir }}"
    state: directory
  when:
    - not quipucords_image_present