---

- name: Start PostgreSQL container with Podman
  shell: "podman run --name {{ db_name }} --network=container:{{ server_name }} -e POSTGRES_USER={{dbms_user}} -e POSTGRES_PASSWORD={{dbms_password}} -v db-data:/var/lib/postgresql/data -d postgres:{{postgres_version}}"
  become: true

- name: Waiting for PostgreSQL to spin up
  pause:
    seconds: 15

- name: Restart the Quipucords server container after starting PostgreSQL
  shell: "podman restart {{ server_name }}"
  become: true