---


- name: Check for PostgreSQL Docker image presence
  shell: "docker images | grep postgres | grep {{ POSTGRES_VERSION }}"
  become: true
  register: postgres_image_raw
  ignore_errors: yes

- name: Set PostgreSQL Docker image presence to false (default)
  set_fact:
    postgres_image_present: false
  when:
    - postgres_image_raw.rc != 0

- name: Set PostgreSQL Docker image presence to true if image present
  set_fact:
    postgres_image_present: "{{ postgres_image_raw['stdout_lines']|length > 0 }}"
  when:
    - postgres_image_raw.rc == 0
    - "'stdout_lines' in postgres_image_raw"

- name: Set variable to indicate that the PostgreSQL Docker image load was not attempted (default)
  set_fact:
    load_postgres_attempted: false

- name: Determine if PostgreSQL Docker Image load required
  set_fact:
    load_postgres_attempted: true
  when:
    - not postgres_image_present
    - find_postgres_image_local.stat.exists == true

- name: Load PostgreSQL Docker image into local image registry
  shell: "docker load -i {{postgres_image_local_path}}"
  become: true
  when:
    - not postgres_image_present
    - find_postgres_image_local.stat.exists == true

- name: Read Docker images and grep for PostgreSQL Docker image
  shell: "docker images | grep postgres | grep {{ POSTGRES_VERSION }}"
  become: true
  register: postgres_image_raw
  ignore_errors: yes
  when:
    load_postgres_attempted|bool

- name: Set PostgreSQL Docker image presence to false (default)
  set_fact:
    postgres_image_present: false
  when:
    - load_postgres_attempted|bool
    - postgres_image_raw.rc != 0

- name: Set PostgreSQL image presence to true if image present
  set_fact:
    postgres_image_present: "{{ postgres_image_raw['stdout_lines']|length > 0 }}"
  when:
    - load_postgres_attempted|bool
    - postgres_image_raw.rc == 0
    - "'stdout_lines' in postgres_image_raw"

- name: Make sure PostgreSQL image loaded (it successfully loaded if skipped)
  fail:
    msg: "The PostgreSQL image was not found."
  when:
    - load_postgres_attempted|bool
    - not postgres_image_present

