---

- name: Check if EPEL is installed
  yum:
    list: epel-release
  register: have_epel_raw
  become: true
  ignore_errors: yes
  when:
    - have_yum|bool

- name: Set have_epel
  set_fact:
    have_epel: "{{ have_epel_raw.results[0].yumstate == 'installed' }}"
  when:
    - have_epel_raw["results"] is defined
    - have_epel_raw["results"]|length > 0

- name: Install EPEL for CentOS/RHEL 6 from internet
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
    state: present
  become: true
  when:
    - is_rhel_centos_6|bool
    - not have_epel

- name: Install EPEL for CentOS/RHEL 7 from internet
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  become: true
  when:
    - is_rhel_centos_7|bool
    - not have_epel

- name: Set the base URL for the QPC CLI yum install (user specified version)
  set_fact:
    cli_github_release_url: "https://github.com/quipucords/qpc/releases/download/{{ cli_version }}"
  when:
    - cli_version is defined

- name: Set the base URL for the QPC CLI yum install (latest version)
  set_fact:
    cli_github_release_url: "https://github.com/quipucords/qpc/releases/latest/download"
  when:
    - cli_version is not defined

- name: Install QPC CLI
  yum:
    name: '{{ cli_github_release_url }}/{{ qpc_package_name }}'
    state: present
  become: true
