---

- name: Setting common default variable values for server installation
  include_role:
    name: server
    tasks_from: init_vars

- name: Validate variable values for server installation
  include_role:
    name: server
    tasks_from: validate_params

- name: Setting common default offline variable values for server installation
  include_role:
    name: server
    tasks_from: init_vars_offline

- name: Validate offline variable values for server installation
  include_role:
    name: server
    tasks_from: validate_params_offline

- name: Set default values for variables of online installation for docker
  include_role:
    name: server_docker
    tasks_from: init_vars

- name: Remove existing docker containers when they are present
  include_role:
    name: server
    tasks_from: uninstall_docker_containers
  when:
    - have_docker

- name: Remove existing podman containers when they are present
  include_role:
    name: server
    tasks_from: uninstall_podman_containers
  when:
    - have_podman

- name: Start Docker service
  include_role:
    name: server_docker
    tasks_from: start_docker_service

- name: Load the PostgreSQL image for offline installation
  include_role:
    name: server_docker
    tasks_from: load_postgres_image_offline

- name: Start the PostgreSQL container
  include_role:
    name: server_docker
    tasks_from: start_postgres_container

- name: Start the QPC server
  include_role:
    name: server_docker
    tasks_from: start_quipucords_container

- name: Validate that the Quipucords server is up and running
  include_role:
    name: server
    tasks_from: validate_server_install